### ISSUE TITLE
[Question] using react-env for S3 based deployments

### ISSUE THREAD

**Issue by shirbr510** [beam-australia/react-env#11]
as far as I understood, the result of using react-env is an nginx container built in with the correct env.js to be hosted in nginx

but, what if you wish to use different deployment environment?
my environment for an example, is S3 based, and deploying the nginx content to a bucket isn't necessarily the best idea.

I have thought of 2 possible solutions and I wanted to advise what is the best solution from your perspective:

1. use the image as is and in the end, extract the `www/var` folder's content and sync only these files.
2. making a PR (to this repo) to abstract the process from nginx and making the usage of nginx optional

p.s: I have to admit that I'm very impressed with what you've accomplished in a month (since initial commit) so kudos to you all 🎉 🚀

**Comment by shirbr510** [comment]
as far as it seems, nothing actually happens unless I'm actively running the nginx image...

I guess I'll need to run `react-env --dest` manually after all :)

**Comment by andrewmclagan** [comment]
Hi. You do not have to use the docker image. This is just to make life easier for those who want to deploy in a docker environment.

The core of this library is a node binary that builds the env.js environment file. That’s all you need. I’m not 100% familiar with deploying to s3... although the core question is: Do you even have environment variables available on s3?? My assumption would be no as you need a node runtime anyway not static js.

Please describe where your env bars come from / config.

**Comment by shirbr510** [comment]
well, it's basically the same
you solution revolves around hosting `env.js` file that you can access from `window._env`
same will happen if you host an `env.js` via an s3 bucket, it will work exactly the same

my point in my question is that it seems like you need more examples on how to build your images with various platforms (and obviously, support `nginx` OOTB)

I actually dug into the way you are using it in nginx and figured out how to implement it all rather neatly

the only thing that I'm missing is that our deployment flow isn't based on the `NODE_ENV` variable due to it's implication on node performance, so we rather use a variable called `ENV` or `REACT_APP_ENV`

**Comment by andrewmclagan** [comment]
That’s a great point we should add some more examples with docker, serverless etc... 

We actually do the same. We have a variable called PLATFORM_ENV so we can still have node in production on our staging servers

**Comment by andrewmclagan** [comment]
Any thoughts on s3 documentation?

**Comment by shirbr510** [comment]
@andrewmclagan if that's the case, let's extract the `NODE_ENV` parameter to a cli parameter that can default to `NODE_ENV` 😄 

I can try and open a PR for you :)

**Comment by shirbr510** [comment]
regarding S3 docs, there's not much to it tbh
the moment you get a dist that includes the correct `env.js` in the build folder, you should be good to go 👍 

I can try and make an example based on a very simple CRA 😄 

but as you said, issues/goals for docs per common deployment way can be very nice 🎉

**Comment by andrewmclagan** [comment]
closing as stale
