### ISSUE TITLE
Limitations Azure Devops

### ISSUE THREAD

**Issue by AnthonyCrowcroft** [beam-australia/react-env#13]
@andrewmclagan I'm currently doing a spike into moving our company onto Azure Dev-ops and atm it currently can only do variable substitutions in JSON or XML would you be open some sort of way we could bind a JSON file instead of going direct to a JS file

**Comment by AnthonyCrowcroft** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops

**Comment by andrewmclagan** [comment]
Sure. Show me what you come up with

**Comment by AnthonyCrowcroft** [comment]
sweeet ill put a pull request together over the weekend. i would expect that it'd be a feature breaking change as the script to include would be slightly different

**Comment by AnthonyCrowcroft** [comment]
@andrewmclagan the code change to output a json file was lovely and easy and updating the tests was fine i was trying to figure out the best way to get it back into the application and all paths are suggesting using a get request, so I'm tossing up between a possibly ugly include script or a function in the index.js of our create react apps simply making a get request to a fixed url of env.json was hoping to get some input from you as to a preference

**Comment by AnthonyCrowcroft** [comment]
My pull request has the starter of a helper function but im needing to connect the github repo to my work so i can check its behaving as expected. do you have any advice it seems to trip up when doing it as github:AnthonyCrowcroft/react-env doesn't seem to work

**Comment by andrewmclagan** [comment]
closing as stale
