### ISSUE TITLE
Type declarations

### ISSUE THREAD

**Issue by AnthonyCrowcroft** [beam-australia/react-env#7]
Hi is there currently a type declaration for this? looking to use this in our solution as a single build that can be deployed to an environment is 100% the best approach for us.

**Comment by andrewmclagan** [comment]
Hello. For sure, I'd accept a PR for this.

**Comment by andrewmclagan** [comment]
Great your PR is merged and should be released as `v2.1.0` thank you

**Comment by AnthonyCrowcroft** [comment]
While the definition is correct I still needed to shim this in so if you'd be happy to reopen it I will do more research to get this pulling through correctly, apologises was to eager to get it done.

**Comment by vimutti77** [comment]
How can I use it. I try to use it like this
```
import env from '@beam-australia/react-env';

export default {
  secret: new URL(env('MY_SECRET')),
};
```
and I got this error
```
Could not find a declaration file for module '@beam-australia/react-env'
```

**Comment by andrewmclagan** [comment]
@AnthonyCrowcroft?

**Comment by AnthonyCrowcroft** [comment]
@vimutti77 if you look within the dist directory there is a types.d.ts file if you copy and paste that into your solution it will work, I'm currently looking into why this isnt being picked up automatically

**Comment by andrewmclagan** [comment]
‘’’json
{
    "name": "awesome",
    "author": "Vandelay Industries",
    "version": "1.0.0",
    "main": "./lib/main.js",
    "types": "./lib/main.d.ts"
}
‘’’

Want to write a PR. You reference them in package json

**Comment by vimutti77** [comment]
@AnthonyCrowcroft Look like if I try to move `types.d.ts` from `node_modules/@beam-australia/react-env/dist` to  `node_modules/@beam-australia/react-env` and rename it to `index.d.ts`. The types will be picked up properly.

**Comment by andrewmclagan** [comment]
Yeah although this is not desirable. We want it to pick them up via package.json

**Comment by andrewmclagan** [comment]
https://github.com/beam-australia/react-env/pull/10

will release as `v2.1.1`

**Comment by andrewmclagan** [comment]
@vimutti77 you can now npm install and use as normal

**Comment by andrewmclagan** [comment]
released: https://www.npmjs.com/package/@beam-australia/react-env

**Comment by AnthonyCrowcroft** [comment]
@andrewmclagan thank you for sorting that man been slammed at work today so wasn't going to get to it till tonight

**Comment by andrewmclagan** [comment]
No problem. Out of interest, you guys using the docker image in this repo for CRA?

**Comment by AnthonyCrowcroft** [comment]
I'm currently not using the docker image as we are react applications within IIS still but future goal is move it to azure blob storage or the likes. The main motivator for us to use the library was to be able to do deployment time injections so we can do a build once deploy anywhere approach
