### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AnthonyCrowcroft** [beam-australia/react-env#9]
I found the examples really helpful when using this for the implementation I was doing but the readme.md doesn't clearly point out the things I needed to do to get it running

**Comment by andrewmclagan** [comment]
Great point. I will take a look at it this week.. Thanks for your input.

**Comment by AnthonyCrowcroft** [comment]
awesome the key parts I found useful from the examples was package.json and that there is a script tag on index.html.

**Comment by andrewmclagan** [comment]
These are already documented in the README.md for create react app. Should it be clearer?

https://github.com/beam-australia/react-env/blob/master/examples/create-react-app/README.md

**Comment by AnthonyCrowcroft** [comment]
the links to the readme i had assumed was just to the example in general... so maybe just a little writing around where the link goes but that page has everything I could have wanted.

**Comment by andrewmclagan** [comment]
Can do

**Comment by andrewmclagan** [comment]
https://github.com/beam-australia/react-env/blob/master/README.md updated with comments (see README.md)
